/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiReceiptRouteImport } from './routes/api/receipt'
import { Route as ApiParse_receiptRouteImport } from './routes/api/parse_receipt'
import { Route as AuthedReceiptRouteImport } from './routes/_authed/receipt'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthedReceiptIndexRouteImport } from './routes/_authed/receipt.index'
import { Route as ApiReceiptIdRouteImport } from './routes/api/receipt.$id'
import { Route as AuthedReceiptReceiptIdRouteImport } from './routes/_authed/receipt.$receiptId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptRoute = ApiReceiptRouteImport.update({
  id: '/api/receipt',
  path: '/api/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParse_receiptRoute = ApiParse_receiptRouteImport.update({
  id: '/api/parse_receipt',
  path: '/api/parse_receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReceiptRoute = AuthedReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReceiptIndexRoute = AuthedReceiptIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedReceiptRoute,
} as any)
const ApiReceiptIdRoute = ApiReceiptIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReceiptRoute,
} as any)
const AuthedReceiptReceiptIdRoute = AuthedReceiptReceiptIdRouteImport.update({
  id: '/$receiptId',
  path: '/$receiptId',
  getParentRoute: () => AuthedReceiptRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthedAppRoute
  '/receipt': typeof AuthedReceiptRouteWithChildren
  '/api/parse_receipt': typeof ApiParse_receiptRoute
  '/api/receipt': typeof ApiReceiptRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/receipt/$receiptId': typeof AuthedReceiptReceiptIdRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
  '/receipt/': typeof AuthedReceiptIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthedAppRoute
  '/api/parse_receipt': typeof ApiParse_receiptRoute
  '/api/receipt': typeof ApiReceiptRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/receipt/$receiptId': typeof AuthedReceiptReceiptIdRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
  '/receipt': typeof AuthedReceiptIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/receipt': typeof AuthedReceiptRouteWithChildren
  '/api/parse_receipt': typeof ApiParse_receiptRoute
  '/api/receipt': typeof ApiReceiptRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/receipt/$receiptId': typeof AuthedReceiptReceiptIdRoute
  '/api/receipt/$id': typeof ApiReceiptIdRoute
  '/_authed/receipt/': typeof AuthedReceiptIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/app'
    | '/receipt'
    | '/api/parse_receipt'
    | '/api/receipt'
    | '/auth/callback'
    | '/receipt/$receiptId'
    | '/api/receipt/$id'
    | '/receipt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/app'
    | '/api/parse_receipt'
    | '/api/receipt'
    | '/auth/callback'
    | '/receipt/$receiptId'
    | '/api/receipt/$id'
    | '/receipt'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/app'
    | '/_authed/receipt'
    | '/api/parse_receipt'
    | '/api/receipt'
    | '/auth/callback'
    | '/_authed/receipt/$receiptId'
    | '/api/receipt/$id'
    | '/_authed/receipt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  ApiParse_receiptRoute: typeof ApiParse_receiptRoute
  ApiReceiptRoute: typeof ApiReceiptRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipt': {
      id: '/api/receipt'
      path: '/api/receipt'
      fullPath: '/api/receipt'
      preLoaderRoute: typeof ApiReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse_receipt': {
      id: '/api/parse_receipt'
      path: '/api/parse_receipt'
      fullPath: '/api/parse_receipt'
      preLoaderRoute: typeof ApiParse_receiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/receipt': {
      id: '/_authed/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof AuthedReceiptRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/receipt/': {
      id: '/_authed/receipt/'
      path: '/'
      fullPath: '/receipt/'
      preLoaderRoute: typeof AuthedReceiptIndexRouteImport
      parentRoute: typeof AuthedReceiptRoute
    }
    '/api/receipt/$id': {
      id: '/api/receipt/$id'
      path: '/$id'
      fullPath: '/api/receipt/$id'
      preLoaderRoute: typeof ApiReceiptIdRouteImport
      parentRoute: typeof ApiReceiptRoute
    }
    '/_authed/receipt/$receiptId': {
      id: '/_authed/receipt/$receiptId'
      path: '/$receiptId'
      fullPath: '/receipt/$receiptId'
      preLoaderRoute: typeof AuthedReceiptReceiptIdRouteImport
      parentRoute: typeof AuthedReceiptRoute
    }
  }
}

interface AuthedReceiptRouteChildren {
  AuthedReceiptReceiptIdRoute: typeof AuthedReceiptReceiptIdRoute
  AuthedReceiptIndexRoute: typeof AuthedReceiptIndexRoute
}

const AuthedReceiptRouteChildren: AuthedReceiptRouteChildren = {
  AuthedReceiptReceiptIdRoute: AuthedReceiptReceiptIdRoute,
  AuthedReceiptIndexRoute: AuthedReceiptIndexRoute,
}

const AuthedReceiptRouteWithChildren = AuthedReceiptRoute._addFileChildren(
  AuthedReceiptRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedReceiptRoute: typeof AuthedReceiptRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRoute,
  AuthedReceiptRoute: AuthedReceiptRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiReceiptRouteChildren {
  ApiReceiptIdRoute: typeof ApiReceiptIdRoute
}

const ApiReceiptRouteChildren: ApiReceiptRouteChildren = {
  ApiReceiptIdRoute: ApiReceiptIdRoute,
}

const ApiReceiptRouteWithChildren = ApiReceiptRoute._addFileChildren(
  ApiReceiptRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  ApiParse_receiptRoute: ApiParse_receiptRoute,
  ApiReceiptRoute: ApiReceiptRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
